services:
  - type: web
    name: upi-fraud-app
    env: python
    build:
      pythonVersion: 3.10.13
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
